### PR TITLE
Enforce integer bounds on ParamInt

### LINKED ISSUE #247: Consider enforcing integer bounds on ParamInt
```r
ParamInt$new("test", lower = 0.1, upper = 0.2)
```
creates an integer param with non-integer bounds; maybe we want to throw an error here because even though there is nothing wrong with this in principle, it is imho an indicator that there is a bug somewhere.

### PR DESCRIPTION
**Pull request by be-marc**
Closes #247

### CODE REVIEW

File: tests/testthat/test_ParamInt.R [hunk 1]
```diff
@@ -14,6 +14,7 @@ test_that("constructor works", {
 
   # check some invalid arg settings
   expect_error(ParamInt$new(id = "x", lower = NULL), "not 'NULL'")
+  expect_error(ParamInt$new(id = "x", lower = 1.5), "not 'double'")
```
Comment (pat-s) [inline tests/testthat/test_ParamInt.R]: Should we also check for the `upper`?

Comment (be-marc) [reply tests/testthat/test_ParamInt.R]: Added two tests for `upper`
